services:
  rabbitmq:
    container_name: lopunny
    image: rabbitmq:4.0.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  mariadb:
    container_name: mariadb
    image: mariadb:11.8.1-noble-rc
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=pokerpai_dev
      - MARIADB_USER=pokerpai_dev
      - MARIADB_PASSWORD=pokerpai_dev
      - MARIADB_DATABASE=pokerpai_dev

volumes:
  rabbitmq_data:
