[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "poker_engine"
version = "0.0.0"
dependencies = [
    "pika>=1.3.2",
    "pokerkit>=0.6.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
]
